spring:
  datasource:
    # 主数据源
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/moon_jpa?serverTimezone=Asia/Shanghai
      username: root
      password:
      type: com.zaxxer.hikari.HikariDataSource
    # 次数据源
    second:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/moon?currentSchema=moon_jpa
      username: moon
      password: moon
  jpa:
    # 主jpa配置
    primary:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update # 每次启动项目时，数据库初始化策略，不自动创建表结构为none
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect # 指定默认的存储引擎为InnoDB，不配置使用 MyISAM 做表的引擎
    # 次jpa配置
    second:
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            auto: update # 每次启动项目时，数据库初始化策略，不自动创建表结构为none
          dialect: org.hibernate.dialect.PostgreSQLDialect