spring:
  application:
    name: spring-boot-logback

  profiles:
    active: dev,mac
server:
  port: 80
#logging:
#  level:
#   root: info

management:
  endpoints:
    web:
      exposure:
        include: loggers,health