spring:
  application:
    name: spring-boot-cookie

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:moon-https-certificate.jks
    key-store-password: moon123
    key-store-type: JKS
  servlet:
    session:
      cookie:
      http-only: true
#        secure: true