server:
  port: 8080
spring:
  redis: # 配置redis
    port: 6379
    host: localhost
    database: 0
    connect-timeout: 5000
    timeout: 1000
    lettuce:
      pool:
        enabled: true
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 100 # 连接池中的最小空闲连接
        max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 单位ms，此处配置30min
